### ISSUE TITLE
Straight to modern era?

### ISSUE THREAD

**Issue by Merion2009** [ArchDuque-Pancake/Tech-Stopper-_Classical_#3]
When I finished the research instead of reaching the Medieval era it took me to the modern era. This has locked some features like the holy warriors for example. I can't research anything but it's really annoying for faith based runs. Idk if it's a bug or anything 
![Screenshot_20240225_115607_Unciv](https://github.com/Caballero-Arepa/Tech-Stopper-_Classical_/assets/154628340/6c717ebf-5ce4-4e2d-acc3-30c6fb1100aa)

**Comment by Caballero-Arepa** [comment]
That is really really weird

**Comment by Caballero-Arepa** [comment]
Try updating now, I believe I have fixed it.

If you can, go back a few turns a see if everything is fine.

**Comment by Merion2009** [comment]
Works 👍
